company/urls.py
"""URLs patterns for company app"""
from django.urls import path

from . import views, views_api

app_name="company"
urlpatterns = [
    # Index page
    path("", views.index, name="index"),
    # Create a company page
    path("company/settings", views.company_settings, name="settings"),
    # Company's Financial year
    path("company/year", views.company_year, name="year"),
    
    # Financial years API
    path("company/api/years", views_api.CompanyYearAPI.as_view(), name="years_api"),
    # Especific f. year API
    path("company/api/years/<int:pk>", views_api.DetailCompanyYearAPI.as_view(),
        name="year_api"),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # Built-in apps
    path("admin/", admin.site.urls),
    # My apps
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("company.urls")),
    path("erp/", include("erp.urls")),
]

erp/urls.py
"""URL patterns for ERP app"""
from django.urls import path

from . import views, views_api

app_name = "erp"
urlpatterns = [
    # Client index webpage
    path("client", views.client_index, name="client_index"),
    # Suppliers webpage
    path("supplier", views.supplier_index, name="supplier_index"),
    # Add a new client or supplier web page
    path("<str:person_type>/new", views.person_new, name="person_new"),
    path("<str:person_type>/new_multiple", views.person_new_multiple, 
        name="person_new_multiple"),
    # Edit existing client or supplier web page
    path("<str:person_type>/edit", views.person_edit, name="person_edit"),
    # Delete a client or supplier web page
    path("<str:person_type>/delete", views.person_delete, name="person_delete"),
    # Show a person's related documents webpage
    path("<str:person_type>/<int:person_pk>/related_documents", 
        views.person_related_docs, name="person_rel_docs"),
    # Show a person's current account webpage
    path("<str:person_type>/current_account", 
        views.person_current_account, name="person_cur_account"),
    path("<str:person_type>/<int:person_pk>/current_account",
        views.person_ca_detail, name="person_ca_detail"),
    
    # Payment conditions
    path("payment_conditions", views.payment_conditions, name="payment_conditions"),
    # Point of sells
    path("points_of_sell", views.point_of_sell, name="points_of_sell"),
    # Document types
    path("document_types", views.doc_types, name="doc_types"),
    # Sales index webpage
    path("sales", views.sales_index, name="sales_index"),
    # Create new sale invoice webpage
    path("sales/invoices/new", views.sales_new, name="sales_new"),
    path("sales/invoices/new_massive", views.sales_new_massive, 
        name="sales_new_massive"),
    # Specific sale invoice webpage
    path("sales/invoices/<int:inv_pk>", views.sales_invoice, name="sales_invoice"),
    # Search invoices webpage
    path("sales/invoices/search", views.sales_search, name="sales_search"),
    # Edit an invoice webpage
    path("sales/invoices/<int:inv_pk>/edit", views.sales_edit, name="sales_edit"),
    # Show an invoice's related receipts webpage
    path("sales/invoices/<int:inv_pk>/related_receipts", views.sales_related_receipts, 
        name="sales_rel_receipts"),
    # Show invoice list
    path("sales/invoices/list", views.sales_list, name="invoice_list"),
    # Receivables index webpage
    path("receivables", views.receivables_index, name="receivables_index"),
    # New Receipt webpage
    path("receivables/receipts/new", views.receivables_new, name="receivables_new"),
    path("receivables/receipts/new_massive", views.receivables_new_massive, 
        name="receivables_new_massive"),
    # Specific sale receipt webpage
    path("receivables/receipts/<int:rec_pk>", views.receivables_receipt, 
        name="receivables_receipt"),
    # Edit a receipt webpage
    path("receivables/receipts/<int:rec_pk>/edit", views.receivables_edit, 
        name="receivables_edit"),
    # Search receipts webpage
    path("receivables/receipts/search", views.receivables_search, 
        name="receivables_search"),
    # Show receipt list
    path("receivables/receipts/list", views.receivables_list, name="receipt_list"),

    # Clients APIs
    path("api/clients", views_api.CompanyClientAPI.as_view(), name="clients_api"),
    path("api/clients/bulk_delete", views_api.CompanyClientDeleteAPI.as_view(),
        name="clients_delete_api"),
    path("api/clients/<int:pk>", views_api.DetailCompanyClientAPI.as_view(), 
        name="client_api"),
    # Suppliers APIS
    path("api/suppliers", views_api.SupplierAPI.as_view(), name="suppliers_api"),
    path("api/suppliers/bulk_delete", views_api.SupplierDeleteAPI.as_view(),
        name="suppliers_delete_api"),
    path("api/suppliers/<int:pk>", views_api.DetailSupplierAPI.as_view(), 
        name="supplier_api"),
    # Payment_conditions APIS
    path("api/payment_conditions/methods", views_api.PaymentMethodAPI.as_view(),
        name="payment_methods_api"), 
    path("api/payment_conditions/methods/<int:pk>", views_api.DetailPaymentMethodAPI.as_view(),
        name="payment_method_api"), 
    path("api/payment_conditions/terms", views_api.PaymentTermAPI.as_view(),
        name="payment_terms_api"),
    path("api/payment_conditions/terms/<int:pk>", views_api.DetailPaymentTermAPI.as_view(),
        name="payment_term_api"),
    # POS APIS
    path("api/points_of_sell", views_api.PointOfSellAPI.as_view(), 
        name="pos_api"),
    path("api/points_of_sell/<int:pk>", views_api.DetailPointOfSellAPI.as_view(), 
        name="detail_pos_api"),
    # Doc Types APIS
    path("api/document_types", views_api.DocTypesAPI.as_view(), 
        name="doc_types_api"),
    path("api/document_types/<int:pk>", views_api.DocTypeAPI.as_view(), 
        name="doc_type_api"),
    # Sale invoices APIs
    path("api/sale_invoices", views_api.SaleInvoicesAPI.as_view(), 
        name="sale_invoices_api"),
    path("api/sale_invoices/bulk_delete", views_api.SaleInvoicesDeleteAPI.as_view(), 
        name="sale_invoices_delete_api"),
    path("api/sale_invoices/<int:pk>", views_api.SaleInvoiceAPI.as_view(), 
        name="sale_invoice_api"),
    # Sale receipts APIs
    path("api/sale_receipts", views_api.SaleReceiptsAPI.as_view(), 
        name="sale_receipts_api"),
    path("api/sale_receipts/bulk_delete", views_api.SaleReceiptsDeleteAPI.as_view(), 
        name="sale_receipts_delete_api"),
    path("api/sale_receipts/<int:pk>", views_api.SaleReceiptAPI.as_view(), 
        name="sale_receipt_api"),


]

templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% endblock title %}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" 
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        {% block link %}{% endblock link %}
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    </head>
    <body>
        <header>
            <nav class="navbar navbar-expand-lg navbar-light bg-body-tertiary">
                <div class="container-fluid">
                    <a class="navbar-brand" href="{% url 'company:index' %}">Company's name</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" 
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" 
                    aria-expanded="false" aria-label="Toggle navigation">
                      <span class="navbar-toggler-icon"></span>
                    </button>
                  <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                      <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="company-menu-link"
                        role="button" aria-current="page" href="#" 
                        data-bs-toggle="dropdown" aria-expanded="false">Company</a>
                        <ul class="dropdown-menu" id="company-menu">
                          <li><a class="dropdown-item" href="{% url 'company:settings' %}">
                          Settings</a></li>
                          <li><a class="dropdown-item" href="{% url 'company:year' %}">
                          Financial Year</a></li>
                          <li><a class="dropdown-item" href="{% url 'erp:points_of_sell' %}">
                          Points of Sell</a></li>
                          <li><a class="dropdown-item" href="{% url 'erp:payment_conditions' %}">
                          Payment Conditions</a></li>
                          <li><a class="dropdown-item" href="{% url 'erp:doc_types' %}">
                          Document Types</a></li>
                        </ul>
                      </li>
                      <li class="nav-item dropdown">
                          <a class="nav-link dropdown-toggle" id="client-menu-link" 
                          role="button" aria-current="page" href="#" 
                          data-bs-toggle="dropdown" aria-expanded="false">Clients</a>
                          <ul class="dropdown-menu" id="client-menu">
                            <li><a class="dropdown-item" href="{% url 'erp:client_index' %}">
                            Overview</a></li>
                            <li><a class="dropdown-item" href="{% url 'erp:person_new' 'client' %}">
                            New</a></li>
                            <li><a class="dropdown-item" href="{% url 'erp:person_edit' 'client' %}">
                            Edit</a></li>
                            <li><a class="dropdown-item" href="{% url 'erp:person_delete' 'client' %}">
                            Delete</a></li>
                            <li><a class="dropdown-item" href="{% url 'erp:person_cur_account' 'client' %}">
                            Current Account</a></li>
                          </ul>
                        </li>
                        <li class="nav-item dropdown">
                          <a class="nav-link dropdown-toggle" id="supplier-menu-link" 
                          role="button" aria-current="page" href="#" 
                          data-bs-toggle="dropdown" aria-expanded="false">Suppliers</a>
                          <ul class="dropdown-menu" id="supplier-menu">
                            <li><a class="dropdown-item" href="{% url 'erp:supplier_index' %}">
                            Overview</a></li>
                            <li><a class="dropdown-item" href="{% url 'erp:person_new' 'supplier' %}">
                            New</a></li>
                            <li><a class="dropdown-item" href="{% url 'erp:person_edit' 'supplier' %}">
                            Edit</a></li>
                            <li><a class="dropdown-item" href="{% url 'erp:person_delete' 'supplier' %}">
                            Delete</a></li>
                            <li><a class="dropdown-item" href="#">
                            Current Account</a></li>
                          </ul>
                        </li>
                        <li class="nav-item dropdown">
                          <a class="nav-link dropdown-toggle" id="sales-menu-link" 
                          role="button" aria-current="page" href="#" 
                          data-bs-toggle="dropdown" aria-expanded="false">Sales</a>
                          <ul class="dropdown-menu" id="sales-menu">
                            <li><a class="dropdown-item" href="{% url 'erp:sales_index' %}">
                            Overview</a></li>
                            <li><a class="dropdown-item" href="{% url 'erp:sales_new' %}">
                            New Invoice</a></li>
                            <li><a class="dropdown-item" href="{% url 'erp:sales_new_massive' %}">
                            New Massive Invoices</a></li>
                            <li><a class="dropdown-item" href="{% url 'erp:sales_search' %}">
                            Search Invoice</a></li>
                            <li><a class="dropdown-item" href="{% url 'erp:invoice_list' %}">
                            Show List</a></li>
                          </ul>
                        </li>
                        <li class="nav-item dropdown">
                          <a class="nav-link dropdown-toggle" id="receivables-menu-link" 
                          role="button" aria-current="page" href="#" 
                          data-bs-toggle="dropdown" aria-expanded="false">Receivables</a>
                          <ul class="dropdown-menu" id="receivables-menu">
                            <li><a class="dropdown-item" href="{% url 'erp:receivables_index' %}">
                            Overview</a></li>
                            <li><a class="dropdown-item" href="{% url 'erp:receivables_new' %}">
                            New Receipt</a></li>
                            <li><a class="dropdown-item" href="{% url 'erp:receivables_new_massive' %}">
                            New Massive Receipts</a></li>
                            <li><a class="dropdown-item" href="{% url 'erp:receivables_search' %}">
                            Search Receipt</a></li>
                            <li><a class="dropdown-item" href="{% url 'erp:receipt_list' %}">
                            Show List</a></li>
                          </ul>
                        </li>
                    </ul>
                    <form class="d-flex" role="search">
                      <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                      <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                  </div>
                </div>
              </nav>
        </header>
        <main>
            <div class="container">
                {% block body %}{% endblock body %}
            </div>
        </main>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" 
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" 
        crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
        {% block script %}{% endblock script %}
    </body>
</html>