company/urls.py
"""URLs patterns for company app"""
from django.urls import path

from . import views, views_api

app_name="company"
urlpatterns = [
    # Index page
    path("", views.index, name="index"),
    # Create a company page
    path("company/settings", views.company_settings, name="settings"),
    # Company's Financial year
    path("company/year", views.company_year, name="year"),
    
    # Financial years API
    path("company/api/years", views_api.CompanyYearAPI.as_view(), name="years_api"),
    # Especific f. year API
    path("company/api/years/<int:pk>", views_api.DetailCompanyYearAPI.as_view(),
        name="year_api"),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # Built-in apps
    path("admin/", admin.site.urls),
    # My apps
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("company.urls")),
    path("erp/", include("erp.urls")),
]

erp/urls.py
"""URL patterns for ERP app"""
from django.urls import path

from . import views, views_api

app_name = "erp"
urlpatterns = [
    # Client index webpage
    path("client", views.client_index, name="client_index"),
    # Suppliers webpage
    path("supplier", views.supplier_index, name="supplier_index"),
    # Add a new client or supplier web page
    path("<str:person_type>/new", views.person_new, name="person_new"),
    path("<str:person_type>/new_multiple", views.person_new_multiple, 
        name="person_new_multiple"),
    # Edit existing client or supplier web page
    path("<str:person_type>/edit", views.person_edit, name="person_edit"),
    # Delete a client or supplier web page
    path("<str:person_type>/delete", views.person_delete, name="person_delete"),
    # Show a person's related documents webpage
    path("<str:person_type>/<int:person_pk>/related_documents", 
        views.person_related_docs, name="person_rel_docs"),
    # Show a person's current account webpage
    path("<str:person_type>/current_account", 
        views.person_current_account, name="person_cur_account"),
    path("<str:person_type>/<int:person_pk>/current_account",
        views.person_ca_detail, name="person_ca_detail"),
    
    # Payment conditions
    path("payment_conditions", views.payment_conditions, name="payment_conditions"),
    # Point of sells
    path("points_of_sell", views.point_of_sell, name="points_of_sell"),
    # Document types
    path("document_types", views.doc_types, name="doc_types"),
    # Sales index webpage
    path("sales", views.sales_index, name="sales_index"),
    # Create new sale invoice webpage
    path("sales/invoices/new", views.sales_new, name="sales_new"),
    path("sales/invoices/new_massive", views.sales_new_massive, 
        name="sales_new_massive"),
    # Specific sale invoice webpage
    path("sales/invoices/<int:inv_pk>", views.sales_invoice, name="sales_invoice"),
    # Search invoices webpage
    path("sales/invoices/search", views.sales_search, name="sales_search"),
    # Edit an invoice webpage
    path("sales/invoices/<int:inv_pk>/edit", views.sales_edit, name="sales_edit"),
    # Show an invoice's related receipts webpage
    path("sales/invoices/<int:inv_pk>/related_receipts", views.sales_related_receipts, 
        name="sales_rel_receipts"),
    # Show invoice list
    path("sales/invoices/list", views.sales_list, name="invoice_list"),
    # Receivables index webpage
    path("receivables", views.receivables_index, name="receivables_index"),
    # New Receipt webpage
    path("receivables/receipts/new", views.receivables_new, name="receivables_new"),
    path("receivables/receipts/new_massive", views.receivables_new_massive, 
        name="receivables_new_massive"),
    # Specific sale receipt webpage
    path("receivables/receipts/<int:rec_pk>", views.receivables_receipt, 
        name="receivables_receipt"),
    # Edit a receipt webpage
    path("receivables/receipts/<int:rec_pk>/edit", views.receivables_edit, 
        name="receivables_edit"),
    # Search receipts webpage
    path("receivables/receipts/search", views.receivables_search, 
        name="receivables_search"),
    # Show receipt list
    path("receivables/receipts/list", views.receivables_list, name="receipt_list"),

    # Clients APIs
    path("api/clients", views_api.CompanyClientAPI.as_view(), name="clients_api"),
    path("api/clients/bulk_delete", views_api.CompanyClientDeleteAPI.as_view(),
        name="clients_delete_api"),
    path("api/clients/<int:pk>", views_api.DetailCompanyClientAPI.as_view(), 
        name="client_api"),
    # Suppliers APIS
    path("api/suppliers", views_api.SupplierAPI.as_view(), name="suppliers_api"),
    path("api/suppliers/bulk_delete", views_api.SupplierDeleteAPI.as_view(),
        name="suppliers_delete_api"),
    path("api/suppliers/<int:pk>", views_api.DetailSupplierAPI.as_view(), 
        name="supplier_api"),
    # Payment_conditions APIS
    path("api/payment_conditions/methods", views_api.PaymentMethodAPI.as_view(),
        name="payment_methods_api"), 
    path("api/payment_conditions/methods/<int:pk>", views_api.DetailPaymentMethodAPI.as_view(),
        name="payment_method_api"), 
    path("api/payment_conditions/terms", views_api.PaymentTermAPI.as_view(),
        name="payment_terms_api"),
    path("api/payment_conditions/terms/<int:pk>", views_api.DetailPaymentTermAPI.as_view(),
        name="payment_term_api"),
    # POS APIS
    path("api/points_of_sell", views_api.PointOfSellAPI.as_view(), 
        name="pos_api"),
    path("api/points_of_sell/<int:pk>", views_api.DetailPointOfSellAPI.as_view(), 
        name="detail_pos_api"),
    # Doc Types APIS
    path("api/document_types", views_api.DocTypesAPI.as_view(), 
        name="doc_types_api"),
    path("api/document_types/<int:pk>", views_api.DocTypeAPI.as_view(), 
        name="doc_type_api"),
    # Sale invoices APIs
    path("api/sale_invoices", views_api.SaleInvoicesAPI.as_view(), 
        name="sale_invoices_api"),
    path("api/sale_invoices/bulk_delete", views_api.SaleInvoicesDeleteAPI.as_view(), 
        name="sale_invoices_delete_api"),
    path("api/sale_invoices/<int:pk>", views_api.SaleInvoiceAPI.as_view(), 
        name="sale_invoice_api"),
    # Sale receipts APIs
    path("api/sale_receipts", views_api.SaleReceiptsAPI.as_view(), 
        name="sale_receipts_api"),
    path("api/sale_receipts/bulk_delete", views_api.SaleReceiptsDeleteAPI.as_view(), 
        name="sale_receipts_delete_api"),
    path("api/sale_receipts/<int:pk>", views_api.SaleReceiptAPI.as_view(), 
        name="sale_receipt_api"),


]

erp/views.py
import csv, os
import pandas as pd
from datetime import datetime, date
from dateutil.relativedelta import relativedelta
from decimal import Decimal
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django.conf import settings
from django.db import transaction, IntegrityError
from django.db.models import Sum, F, Count
from django.db.models.functions import Coalesce
from django.http import HttpResponseRedirect, Http404, HttpResponseBadRequest
from django.shortcuts import render
from django.urls import reverse
from pathlib import Path



from company.models import FinancialYear, PersonModel
from .forms import (CclientForm, SupplierForm, PaymentMethodForm, PaymentTermForm, 
    PointOfSellForm, SaleInvoiceForm, SaleInvoiceLineFormSet, SearchInvoiceForm,
    AddPersonFileForm, AddSaleInvoicesFileForm, SearchByYearForm, SearchByDateForm,
    SaleReceiptForm, SearchReceiptForm, AddSaleReceiptsFileForm, cutOffDateForm)
from .models import (Company, CompanyClient, Supplier, PaymentMethod, 
    PaymentTerm, PointOfSell, DocumentType, SaleInvoice, SaleInvoiceLine,
    SaleReceipt, PurchaseInvoice, PurchaseReceipt, ClientCurrentAccount)
from .utils import (read_uploaded_file, check_column_len, standarize_dataframe,
check_column_names, list_file_errors, get_model_fields_name, get_sale_invoice_objects,
update_invoice_collected_status, get_financial_calendar_dates)


# Create your views here.

def client_index(request):
    """Client's overview page"""

    # Get total clients
    clients = CompanyClient.objects.all()

    # Get global sums of sales and receuvables
    total_sales = SaleInvoice.objects.aggregate(
        lines_sum=Sum("s_invoice_lines__total_amount")
    )["lines_sum"] or 0
    total_receivables = SaleReceipt.objects.aggregate(
        total_sum=Sum("total_amount")
    )["total_sum"] or 0

    # Add sales and transaction to each client
    clients_with_sales = ClientCurrentAccount.objects.exclude(
        invoice__isnull=True).values(
            "client__id", "client__name", "client__tax_number").annotate(
                total_sales=Coalesce(Sum("amount"), Decimal(0)),
                transactions=Coalesce(Count('id'), 0)
            )
    # If there are clients, create a dict to contain all the necessary data
    if clients:
        clients_dict = {
            "total_sales": total_sales,
            "total_receivables": total_receivables,
            "uncollected_amount": ClientCurrentAccount.objects.aggregate(
                total_sum=Sum("amount"))["total_sum"] or 0,
            "by_last_added": clients,
            "by_amount": clients_with_sales.order_by("-total_sales"),
            "by_transactions": clients_with_sales.order_by("-transactions"),
        }
    
    return render(request, "erp/client_index.html", {
        "clients_dict": clients_dict or None,
    })


def person_new(request, person_type):
    """Add a new client/supplier page"""
    # File form post works in a dif view, so it is not filled in this view
    file_form = AddPersonFileForm()
    if person_type == "client":
        form = CclientForm
    else:
        form = SupplierForm

    if request.method == "POST":
        person_form = form(request.POST)
        if person_form.is_valid():
            person_form.save()
            return HttpResponseRedirect(reverse(f"erp:{person_type}_index"))
    else:
        person_form = form()

    return render(request, "erp/person_new.html", {
        "form": person_form,
        "file_form": file_form,
        "person_type": person_type,
    })


def person_new_multiple(request, person_type):
    """Add multiple clients/suppliers"""
    if request.method == "POST":
        file_form = AddPersonFileForm(request.POST, request.FILES)
        
        if file_form.is_valid():
            file = request.FILES["file"]
            
            # Read file according to the extension    
            df = read_uploaded_file(file)
            
            # Check all columns exist and Standarize columns names and blanks
            try: 
                check_column_len(df, 5)
                df = standarize_dataframe(df)
                person_fields = get_model_fields_name(PersonModel)
                check_column_names(df, person_fields)
            except ValueError:
                return HttpResponseBadRequest(
                    f"The columns in your file don't match the required format."
                )
            

            # Pass all values in model
            try:
                with transaction.atomic():
                    for index, row in df.iterrows():
                        # Convert number fields into string to allow me using
                        # validators
                        person_fields_row = list(map(str, row[person_fields]))

                        if person_type == "client":
                            person_model = CompanyClient
                        elif person_type == "supplier":
                            person_model = Supplier
                        new_person = person_model(
                            tax_number = person_fields_row[0],
                            name = person_fields_row[1],
                            address = person_fields_row[2],    
                            email = person_fields_row[3],
                            phone = person_fields_row[4],
                        )
                        
                        # Execute validators before saving, and show error if exists,
                        try:
                            new_person.full_clean()
                            new_person.save()
                        except ValidationError as ve:
                            # Value error is raised for atomic transaction
                            raise ValueError(list_file_errors(ve, index))
            except ValueError as ve:
                return HttpResponseBadRequest(str(ve))

            # If everything is correct
            return HttpResponseRedirect(reverse(f"erp:{person_type}_index"))
        else:
            return HttpResponseBadRequest("Invalid file.")
    else:
        return HttpResponseRedirect(reverse(f"erp:person_new", 
            kwargs={"person_type": person_type}))


def person_edit(request, person_type):
    """Search and edit an existing client or supplier"""
    if request.method == "GET":
        if person_type == "client":
            model = CompanyClient
            form = CclientForm
        elif person_type == "supplier":
            model = Supplier
            form = SupplierForm

        person_list = model.objects.all()
        person_form = form()   
        
        return render(request, "erp/person_edit.html", {
            "person_list": person_list,
            "form": person_form,
            "person_type": person_type,
        })


def person_delete(request, person_type):
    """Search and delete an existing client or supplier"""
    if person_type == "client":
        model = CompanyClient
        form = CclientForm
    elif person_type == "supplier":
        model = Supplier
        form = SupplierForm

    person_list = model.objects.all()
    person_form = form()
    
    return render(request, "erp/person_delete.html", {
        "person_list": person_list,
        "form": person_form,
        "person_type": person_type,
    })

def person_related_docs(request, person_type, person_pk):
    """ Show related invoices and receipts of a client or supplier webpage."""
    
    if person_type == "client":
        person_model = CompanyClient
        inv_model = SaleInvoice
        rec_model = SaleReceipt
    else:
        person_model = Supplier
        inv_model = PurchaseInvoice
        rec_model = PurchaseReceipt

    person = person_model.objects.get(pk=person_pk)
    invoice_list = inv_model.objects.filter(recipient=person)
    receipt_list = rec_model.objects.filter(recipient=person)

    return render(request, "erp/person_related_docs.html", {
        "person_type": person_type,
        "person": person,
        "invoice_list": invoice_list,
        "receipt_list": receipt_list,
    })

def person_current_account(request, person_type):
    """Clients/Supplier's current account"""
    financial_year = FinancialYear.objects.filter(current=True).first()
    cur_year = int(financial_year.year)
    prev_year = int(financial_year.year) - 1

    if request.method == "POST":
        form_cutoff = cutOffDateForm(request.POST)
        if form_cutoff.is_valid():
            day = form_cutoff.cleaned_data["day"]
            month = form_cutoff.cleaned_data["month"]
            
            # Check day and month are correct and add default date otherwise
            try:
                datetime(cur_year, month, day)
            except ValueError:
                form_cutoff.add_error(
                    "day", "The date is invalid."
                )
                day = 31
                month = 12

            clients_current_ca = ClientCurrentAccount.objects.filter(
                    date__lte=datetime(cur_year, month, day)
            ).values("client", "client__name", 'client__tax_number').annotate(
                global_balance=Coalesce(Sum("amount"), Decimal(0))
            ).order_by("-date")
        
            clients_prev_ca = ClientCurrentAccount.objects.filter(
                    date__lte=datetime(prev_year, month, day)
            ).values("client", "client__name", 'client__tax_number').annotate(
                global_balance=Coalesce(Sum("amount"), Decimal(0))
            ).order_by("-date")
            
       
    else:
        # current year cca
        day = 31
        month = 12
        clients_current_ca = ClientCurrentAccount.objects.filter(
            date__lte=datetime(cur_year, month, day)
        ).values("client", "client__name", 'client__tax_number').annotate(
            global_balance=Coalesce(Sum("amount"), Decimal(0))
        ).order_by("-global_balance")
        # previous year cca

templates/erp/person_ca_detail.html
{% extends "layout.html" %}
{% load static %}

{% block title %}{{ client.name }} Current Account {% endblock title %}

{% block body %}
    <br>
    <h3>{{ client.name }} Current Account</h3>
    <h6>Amount: $ {{ total_client_ca|floatformat:2 }}</h6>
    <br>
    
    <div class="container-fluid">
        <h5>Range of Time</h5>
        <ul class="nav nav-tabs" id="myTab" role="tablist">
            <li class="nav-item" role="presentation">
              <button class="nav-link active" id="date-tab" data-bs-toggle="tab"
               data-bs-target="#date-tab-pane" type="button" role="tab" aria-controls="date-tab-pane"
               aria-selected="true">By Date</button>
            </li>
            <li class="nav-item" role="presentation">
              <button class="nav-link" id="year-tab" data-bs-toggle="tab" data-bs-target="#year-tab-pane"
              type="button" role="tab" aria-controls="year-tab-pane" aria-selected="false">
              By Year</button>
            </li>
        </ul>
        <div class="tab-content" id="section-search">
            <div class="tab-pane fade show active" id="date-tab-pane" role="tabpanel"
            aria-labelledby="date-tab" tabindex="0">
                <form action="{% url 'erp:person_ca_detail' person_type client.id %}" method="POST">
                    {% csrf_token %}
                    {{ form_date.as_p }}
                    <input type="hidden" name="form_type" value="date">
                    <input type="submit" value="Search">
                </form>
            </div>
            <div class="tab-pane fade" id="year-tab-pane" role="tabpanel" 
            aria-labelledby="year-tab" tabindex="0">
                <form action="{% url 'erp:person_ca_detail' person_type client.id %}" method="POST">
                    {% csrf_token %}
                    {{ form_year.as_p }}
                    <input type="hidden" name="form_type" value="year">
                    <input type="submit" value="Search">
                </form>
            </div>
        </div>
    </div>
    <br>
    {% if client_ca %}
        <div id="transactions-section" class="container-fluid">
            <div class="row justify-content-center align-items-center w-75" id="pca-headers">
                <div class="header col-2">DATE</div>
                <div class="header col-5">DETAIL</div>
                <div class="header col-3">AMOUNT</div>
            </div>
            <br>
            {% for transaction in client_ca %}
                <div class="transaction row">
                    <div class="col-2 date-val">{{ transaction.date|date:"d/m/Y" }}</div>
                    {% if transaction.invoice %}
                        <div class="col-5 detail-val">
                            (I) <a href="{{ transaction.invoice.get_absolute_url }}">{{ transaction.invoice }}</a></div>
                    {% elif transaction.receipt %}
                        <div class="col-5 detail-val">
                            (R) <a href="{{ transaction.receipt.get_absolute_url }}">{{ transaction.receipt }}</a></div>
                    {% else %}    
                        <div class="col-5 detail-val">INITIAL ENTRY</div>
                    {% endif %}
                    <div class="col-3 amount-val" >$ {{ transaction.amount }}</div>
                </div>
            {% endfor %}
            <div class="row" id="total-section">
                <div class="col-2"></div><div class="col-5 text-end">BALANCE</div>
                <div class="col-3 total-val">$ {{ total_client_ca|floatformat:2 }}</div>
            </div>
    {% else %}
        <p class="text-center">There wasn't any transaction during this period of time.</p>
    {% endif %}
    </div>

{% endblock body %}

templates/erp/person_current_account.html
{% extends "layout.html" %}
{% load static %}

{% block title %}{{ person_type|capfirst }} Current Account {% endblock title %}

{% block body %}

    <h3>Client Current Account</h3>

    <ul class="nav nav-pills justify-content-start mb-4" id="main-tab-section" 
    role="tablist">
        <li class="nav-item me-4 disabled" role="presentation">
            <button class="nav-link" id="hide-tab" data-bs-toggle="tab" 
            data-bs-target="#tab1" data-condition="method" type="button" role="tab" 
            aria-controls="tab1" aria-selected="false" data-clicked="false">
            Hide Settled Accounts</button>
        </li>
        <li class="nav-item" role="presentation">
            <button class="nav-link" id="search-tab" data-bs-toggle="tab" 
            data-bs-target="#tab2" data-condition="term" type="button" role="tab" 
            aria-controls="tab2" aria-selected="false" data-clicked="false">
            Search {{ person_type|capfirst }} CA</button>
        </li>
        <li class="nav-item" role="presentation">
            <button class="nav-link" id="cutoff-tab" data-bs-toggle="tab" 
            data-bs-target="#cutoff-tab-pane" data-condition="term" type="button" role="tab" 
            aria-controls="cutoff-tab-pane" aria-selected="false" data-clicked="false">
            Cut-off Date</button>
        </li>
    </ul>
    <div class="tab-content" id="cutoff-section">
        <div class="tab-pane fade" id="cutoff-tab-pane" role="tabpanel"
        aria-labelledby="cutoff-tab" tabindex="2">
            <form action="{% url 'erp:person_cur_account' person_type %}" method="POST">
                {% csrf_token %}
                {{ form_cutoff.as_p }}
                <input type="hidden" name="form_type" value="date">
                <input type="submit" value="search">
            </form>
        </div>
    </div>
    <br>
    <div class="container-fluid">
        <div class="row">
            <div class="col-5">
                <h5>Current account by {{ cutoff }}/{{ current_year.year }}</h5>
                <h6>$ {{ total_clients|floatformat:2 }}</h6>
            </div>
            <div class="col-1"></div>
            <div class="col-5">
                <h5>Current account by {{ cutoff }}/{{ current_year.year|add:"-1" }}</h5>
                <h6>$ {{ total_clients_prev|floatformat:2 }}</h6>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-5 left-side">
                <div class="row headers">
                    <div class="col-4" data-reverse="false">{{ person_type|capfirst }}</div>
                    <div class="col-4" data-reverse="false">Tax Number</div>
                    <div class="col-4" data-reverse="false">Balance</div>
                </div>
                <div class="ca-list">
                    {% for client in clients_current_ca %}
                        <div class="specific-person row">
                            <div class="col-4">{{ client.client__name }}</div>
                            <div class="col-4">{{ client.client__tax_number }}</div>
                            <div class="col-4">$ {{ client.global_balance|floatformat:2 }}</div>
                        </div>
                    {% empty %}
                        <p>You haven't added any {{ person_type }} yet.</p>   
                    {% endfor %}
                </div>
            </div>
            <div class="col-1"></div>
            <div class="col-5 right-side">
                <div class="row headers">
                    <div class="col-4" data-reverse="false">{{ person_type|capfirst }}</div>
                    <div class="col-4" data-reverse="false">Tax Number</div>
                    <div class="col-4" data-reverse="false">Balance</div>
                </div>
                <div class="ca-list">
                {% for client in clients_prev_ca %}
                    <div class="specific-person row">
                        <div class="col-4">{{ client.client__name }}</div>
                        <div class="col-4">{{ client.client__tax_number }}</div>
                        <div class="col-4">$ {{ client.global_balance|floatformat:2 }}</div>
                    </div>
                {% empty %}]
                    <p>You haven't added any {{ person_type }} yet.</p>   
                {% endfor %}
                </div>
            </div>
        </div>
    </div>
    
{% endblock body %}

{% block script %}

    <script src="{% static 'js/person_current_account.js' %}"></script>
    <script src="{% static 'js/utils.js' %}"></script>
    <script src="{% static 'js/crud.js' %}"></script>
    
{% endblock script %}

templates/erp/person_new.html
{% extends "layout.html" %}

{% block title %}New {{ person_type|capfirst }}{% endblock title %}

{% block body %}

    <div class="container-fluid">
        <div class="row">
            <div class="col-6">
                <h2>New {{ person_type|capfirst }}</h2>
                <form action="{% url 'erp:person_new' person_type %}" method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" value="Add">
                </form>
            </div>
            <div class="col-6">
                <h2>Add Multiple {{ person_type|capfirst }}s</h2>
                <p>Available extensions: .xls, .xlsx, .csv.</p>
                <form action="{% url 'erp:person_new_multiple' person_type %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ file_form.as_p }}
                    <input type="submit" value="Upload">
                </form>
            </div>
        </div>
    </div>

{% endblock body %}

templates/erp/receivables_edit.html
{% extends "erp/receivables_new.html" %}

{% block title %}Edit Receipt{% endblock title %}

{% block edit_title %}
    <h3 id="document-title" data-document="receipt" data-action="edit">
        Edit Receipt <span class="smaller-text">{{ receipt }}</span></h3>
    <p id="receipt-link" data-receipt="{{ receipt.pk }}">
        Go to <a href="{{ receipt.get_absolute_url }}">receipt detail</a>.
    </p>    
{% endblock edit_title %}

{% block edit_form_action %}{% url 'erp:receivables_edit' receipt.pk %}{% endblock edit_form_action %}

{% block edit_input_submit %}
    <input type="submit" value="Edit">
{% endblock edit_input_submit %}

templates/erp/receivables_new_massive.html
{% extends "erp/document_new_massive.html" %}

{% block url %}{%  url 'erp:receivables_new_massive' %}{% endblock url %}

templates/erp/sales_edit.html
{% extends "erp/sales_new.html" %}

{% block title %}Edit Invoice{% endblock title %}

{% block edit_title %}
    <h3 id="document-title" data-document="invoice" data-action="edit">
        Edit Invoice <span class="smaller-text">{{ invoice }}</span></h3>
    
    <p id="invoice-link">
        Go to <a href="{{ invoice.get_absolute_url }}">invoice detail</a>.
    </p>    
{% endblock edit_title %}

{% block edit_form_action %}{% url 'erp:sales_edit' invoice.pk %}{% endblock edit_form_action %}

{% block edit_line_formset %}
    {% for line_form in line_formset %}
        {% if line_form.instance.pk %}
            {{ line_form.as_p }}
        {% endif %}
    {% endfor %}
{% endblock edit_line_formset %}

{% block edit_input_submit %}
    <input type="submit" value="Edit">
{% endblock edit_input_submit %}

templates/erp/sales_invoice.html
{% extends "layout.html" %}
{% load static %}

{% block title %}
    Invoice {{ invoice }}
{% endblock title %}

{% block body %}

    <h2>{{ invoice.type.description }} N° {{ invoice.point_of_sell }}-{{ invoice.number }}</h2>
    {% if invoice.collected %}<small>Collected</small>{% endif %}
    
    <a id="edit-button" class="edit-button" href="{% url 'erp:sales_edit' invoice.pk %}">Edit</a>
    <button id="delete-button" data-document="invoice" data-id="{{ invoice.id }}" 
    data-type="{{ invoice.type.type }}" data-pos="{{ invoice.point_of_sell }}" 
    data-number="{{ invoice.number }}">Delete</button>
    <br>
    <div class="container-fluid">
        <div class="row">
            <div class="col-5"> 
                <h3>{{ invoice.sender.name }}</h3>
                <p><b>Sender:</b> {{ invoice.sender.name }}</p>
                <p><b>Address:</b> {{ invoice.sender.address }}</p>  
            </div>
            <div class="col-2">
                <h1>{{ invoice.type.type }}</h1>
                <p>{{ invoice.type.code }}</p>
            </div>
            <div class="col-5">
                <h3>{{ invoice.type.description }}</h3>
                <p><b>Point of Sell:</b> {{ invoice.point_of_sell }} <b>Invoice Number:</b> 
                {{ invoice.number }}
                </p>
                <p><b>Issue Date:</b> {{ invoice.issue_date|date:"d/m/Y" }}</p>
                <p><b>Tax Number:</b> {{ invoice.sender.tax_number }}</p>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-5"> 
                <p><b>Tax Number:</b> {{ invoice.recipient.tax_number }}</p>
                <p><b>Payment Method:</b> {{ invoice.payment_method }}</p>
            </div>
            <div class="col-2"></div>
            <div class="col-5">
                <p><b>Name:</b> {{ invoice.recipient.name }}</p>
                <p><b>Address:</b> {{ invoice.recipient.address }}</p>
                <p><b>Payment Term:</b> {{ invoice.payment_term }}</p>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-4">
                <p><b>Description</b></p>
                {% for line in invoice.s_invoice_lines.all %}
                    <p> {{ line.description }} </p>
                {% endfor %}
            </div>
            <div class="col-2">
                <p><b>Not Taxable</b></p>
                {% for line in invoice.s_invoice_lines.all %}
                    <p>$ {{ line.not_taxable_amount }}</p>
                {% endfor %}
            </div>
            <div class="col-2">
                <p><b>Taxable</b></p>
                {% for line in invoice.s_invoice_lines.all %}
                    <p>$ {{ line.taxable_amount }}</p>
                {% endfor %}
            </div>
            <div class="col-2">
                <p><b>VAT</b></p>
                {% for line in invoice.s_invoice_lines.all %}
                    <p>$ {{ line.vat_amount }}</p>
                {% endfor %}
            </div>
            <div class="col-2">
                <p><b>Subtotal</b></p>
                {% for line in invoice.s_invoice_lines.all %}
                    <p>$ {{ line.total_amount }}</p>
                {% endfor %}
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-8"></div>
            <div class="col-2">
                <p><b>TOTAL</b></p>
            </div>
            <div class="col-2">
                <p>$ {{ invoice.total_lines_sum }}</p>
            </div>
        </div>
    </div>

{% endblock body %}

{% block script %}
    <script src="{% static 'js/document_detail.js' %}"></script>
    <script src="{% static 'js/document_delete.js' %}"></script>
    <script src="{% static 'js/crud.js' %}"></script>
    <script src="{% static 'js/utils.js' %}"></script>
{% endblock script %}